### ISSUE TITLE
Numbers for ICL

### ISSUE THREAD

**Issue by goldsteinn** [travisdowns/x86-loop-test#3]
[results-icl.txt](https://github.com/travisdowns/x86-loop-test/files/5979078/results-icl.txt)

**Comment by travisdowns** [comment]
Thanks, taking a look.

**Comment by travisdowns** [comment]
@goldsteinn it looks like the problem is that for uop counts above ~38, the LSD is only working for _odd_ numbers of uops:

![image](https://user-images.githubusercontent.com/2403521/107898174-dd253200-6f19-11eb-9c36-381de498f7c6.png)

**Comment by travisdowns** [comment]
Blue being cases served out of the LSD (in your results) and red from the legacy decoder. Not sure why this is, perhaps something to do with the way lines get banished from the uop cache for having too many ops

**Comment by goldsteinn** [comment]
@travisdowns That is strange for N >= 38. 

Your graph doesn't seem to show performance varying by uops % N but looking at the data I see that. Perhaps I am not understanding that data properly?

In ```Running short_nop_aligned from 3 to 200``` for uops in N = [10, 25] I see ins / cycle varying by N % 5

```
1000136191,,instructions:u,56617150,100.00,4.93,insn per cycle
1000315963,,lsd_uops,56617150,100.00,,
670972,,idq_dsb_uops,56617150,100.00,,
235128380,,cycles:u,64735764,100.00,,
1100136194,,instructions:u,64735764,100.00,4.68,insn per cycle
1100056097,,lsd_uops,64735764,100.00,,
620709,,idq_dsb_uops,64735764,100.00,,
267962896,,cycles:u,73960785,100.00,,
1200136168,,instructions:u,73960785,100.00,4.48,insn per cycle <---- % 5 == 2 higher ins / cycle than next line but less total instructions so would expect lower cycles / iteration in your graph
1199987014,,lsd_uops,73960785,100.00,,
604312,,idq_dsb_uops,73960785,100.00,,
301401924,,cycles:u,83382860,100.00,,
1300136210,,instructions:u,83382860,100.00,4.31,insn per cycle <---- % 5 == 3 is trough
1299969316,,lsd_uops,83382860,100.00,,
611370,,idq_dsb_uops,83382860,100.00,,
302519885,,cycles:u,84177006,100.00,,
1400136199,,instructions:u,84177006,100.00,4.63,insn per cycle
1400140095,,lsd_uops,84177006,100.00,,
671464,,idq_dsb_uops,84177006,100.00,,
302093674,,cycles:u,84219383,100.00,,
1500136199,,instructions:u,84219383,100.00,4.97,insn per cycle
1499999854,,lsd_uops,84219383,100.00,,
645005,,idq_dsb_uops,84219383,100.00,,
351254430,,cycles:u,96375073,100.00,,
1600136187,,instructions:u,96375073,100.00,4.56,insn per cycle
1599957104,,lsd_uops,96375073,100.00,,
629188,,idq_dsb_uops,96375073,100.00,,
352096870,,cycles:u,97712238,100.00,,
1700136255,,instructions:u,97712238,100.00,4.83,insn per cycle <---- % 5 == 2 higher ins / cycle than next line but less total instructions so would expect lower cycles / iteration in your graph
1699928885,,lsd_uops,97712238,100.00,,
661385,,idq_dsb_uops,97712238,100.00,,
402817799,,cycles:u,111714513,100.00,,
1800136212,,instructions:u,111714513,100.00,4.47,insn per cycle <---- % 5 == 3 is trough
1800024624,,lsd_uops,111714513,100.00,,
680970,,idq_dsb_uops,111714513,100.00,,
403419801,,cycles:u,112132387,100.00,,
1900136212,,instructions:u,112132387,100.00,4.71,insn per cycle
1900046764,,lsd_uops,112132387,100.00,,
694384,,idq_dsb_uops,112132387,100.00,,
401972925,,cycles:u,110522017,100.00,,
2000136203,,instructions:u,110522017,100.00,4.98,insn per cycle
1999941606,,lsd_uops,110522017,100.00,,
640345,,idq_dsb_uops,110522017,100.00,,
455785320,,cycles:u,126054460,100.00,,
2100136206,,instructions:u,126054460,100.00,4.61,insn per cycle
2099953173,,lsd_uops,126054460,100.00,,
805714,,idq_dsb_uops,126054460,100.00,,
453952224,,cycles:u,127270831,100.00,,
2200136220,,instructions:u,127270831,100.00,4.85,insn per cycle <---- % 5 == 2 higher ins / cycle than next line but less total instructions so would expect lower cycles / iteration in your graph
2199850126,,lsd_uops,127270831,100.00,,
707864,,idq_dsb_uops,127270831,100.00,,
505011302,,cycles:u,139922328,100.00,,
2300136200,,instructions:u,139922328,100.00,4.55,insn per cycle <---- % 5 == 3 is trough
2299673700,,lsd_uops,139922328,100.00,,
929136,,idq_dsb_uops,139922328,100.00,,
502846923,,cycles:u,139420929,100.00,,
2400136211,,instructions:u,139420929,100.00,4.77,insn per cycle
2399584238,,lsd_uops,139420929,100.00,,
693484,,idq_dsb_uops,139420929,100.00,,
501946672,,cycles:u,140228742,100.00,,
2500136202,,instructions:u,140228742,100.00,4.98,insn per cycle
```

**Comment by travisdowns** [comment]
I'm plotting just cycles, not instructions/cycle, which might explain the discrepancy? 

Here's the spreadsheet I used, look only at the first tab (the rest are still Skylake numbers). I just copied the data from the results file you used above.

I think cycles is clearer because cycles will tend to follow a more obvious pattern since it mostly proceeds in a monotonic way with integral values. Dividing by instructions (which vary for every test), just confuses things a bit?


[icelake.zip](https://github.com/travisdowns/x86-loop-test/files/5979742/icelake.zip)

**Comment by travisdowns** [comment]
@goldsteinn - I took another look and I think the plot is correct, and it seems to reflect a 2x unroll in the LSD. That is, the performance is as if two copies of the loop are in the LSD, and then one applies the rule that the full LSD takes an integer number of cycles (specifically, `ceiling(uops/5)` cycles) to execute.

So at 22 uops, you unroll to 44, which takes `ceil(44/5) = 9` cycles to execute (two iterations), or 4.5 cycles as the data you annotated shows. At 23 uops, it's `ceil(46/5) = 10` or 5 cycles per iteration, as the data shows.

Here's the same plot as above, but zoomed in on the region of interest, and with the red line added which indicates the theoretical performance based on the 2x unroll as described above. It's an exact match between 13 and 30 uops (after which the unroll presumably stops).

![image](https://user-images.githubusercontent.com/2403521/107997232-051ba080-6fc1-11eb-9dc3-732987dea0f1.png)

Below 13 uops, maybe the loop is unrolled more times in the LSD, I didn't check if that makes the measurements match up. For small loops there are other effects too, e.g., branch prediction has a maximum throughput which depends on a few factors.

**Comment by goldsteinn** [comment]
@travisdowns I see. 2x unroll would also explain why % 5 == 3 performed worst because diff between ceil and actual value is max there. 

From [8, 12] it seems to be unroll 3x theoretical corresponds
From [5, 7] it seems unroll 4x theoretical corresponds

the icelake LSD is 70 uops in size so I'm not seeing where the boundaries of 7 and 13 come from for 4x, 3x, or 2x unroll.

**Comment by travisdowns** [comment]
There's still the mystery of why the loop falls out of the LSD for even values, but that could also be related to the test construction. IIRC this behavior is fairly fragile in that the rule is "no more than 18 uops in a 32B region" but if the CPU never even decodes part of the 32B region (e.g. because it is never on the predicted path of execution) then you can bypass the rule (if the decoded uops are fewer than 18). So things like prefetching and branch prediction can play a role in the caching in microbenchmarks like this. 

It could also just be how the functions end up in their alignment.

**Comment by goldsteinn** [comment]
:/ "The more I learn, the more I realize how much I don't know"

Thanks for taking the time look through the data with me. Are you planning to update your answer for icelake? (want to know if I should be keeping an eye on it)

The <= 13 case seems almost as though its ideal uops / cycle. 

Kind of reminds me of:
> If the count is even and less than 32, you're good, except if it's 10 in which case you should unroll to another even number if you can.

9 is some weird case you should unroll 1 more time, and 32 -> ~[30, 38].

**Comment by travisdowns** [comment]
> The <= 13 case seems almost as though its ideal uops / cycle.

Hmm, depends on your definition of almost? Here's a chart showing the "overhead" (how many more cycles than optimal, where optimal is uops/5):

![image](https://user-images.githubusercontent.com/2403521/108035794-235fbb80-7016-11eb-8d47-6e2ef1aa7e13.png)

Green bars are overhead (on the right y axis). 13 and below don't look particularly good - even slightly worse than the later ones in a relative sense. 3 and 4 uops are terrible just because no loop can execute faster than 1 cycle/iter (taken branch limitation).

On the first chart < 13 looks pretty good, but it's not easy to eyeball and while the absolute differences are small, the relative overheads aren't great.

> Are you planning to update your answer for icelake? (want to know if I should be keeping an eye on it)

It crossed my mind, but it's a bit of work and I think I'm already at the character limit so would have to create a separate answer.

The case we've looked at "aligned short nop" I think is actually the least interesting case. The short nop is supposed to break out of the LSD (but the way it does so is quite different than Skylake, apparently, per the above) but in real life that's not going to happen much. The long nop case, which is either in LSD or DSB depending on loop size is more reflective of real life.

Maybe one day I'll get around it :)

**Comment by goldsteinn** [comment]
I appreciated the update: https://www.realworldtech.com/forum/?threadid=191707&curpostid=200320 :)

Though the rub appears to be the ItoM events are grouped with all other RFO events. https://github.com/erikarn/intel-pcm/blob/master/src/pcm-pcie.cpp is the only example I can find of isolating ItoM by MSR samples. Only issue they don't support icelake yet and still searching for MSR offset, but you sent me in the right direction :)

**Comment by travisdowns** [comment]
@goldsteinn is your comment related to small loop handling on ICL or another discussion?

**Comment by goldsteinn** [comment]
No, just saw you where posting on the thread and had prefaced your comment with:
> Probably nobody is waiting for an update this almost a year later, but I though I'd link this thread here.

I wasn't necessarily waiting for it, but appreciated it :)

sorry if thats spam.

**Comment by travisdowns** [comment]
@goldsteinn - ah OK, makes sense and thanks for the clarification. Definitely not "spam", so no worries!
